"""Method registry for experiment pipelines and reserved baselines."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class MethodSpec:
    """High-level method interface used by scripts and documentation."""

    name: str
    display_name: str
    implemented: bool
    pipeline_steps: tuple[str, ...]
    todo: tuple[str, ...] = ()
    integration_notes: tuple[str, ...] = ()


METHOD_REGISTRY: dict[str, MethodSpec] = {
    "base": MethodSpec(
        name="base",
        display_name="Base",
        implemented=True,
        pipeline_steps=("run_caption.py", "run_pope.py"),
    ),
    "verify_all": MethodSpec(
        name="verify_all",
        display_name="Verify-All",
        implemented=True,
        pipeline_steps=("extract_objects.py", "verify_objects.py --method verify_all", "revise_captions.py"),
    ),
    "random_verify": MethodSpec(
        name="random_verify",
        display_name="Random-Verify",
        implemented=True,
        pipeline_steps=(
            "extract_objects.py",
            "verify_objects.py --method random_verify --reference <svo_verifications>",
            "revise_captions.py",
        ),
    ),
    "svo": MethodSpec(
        name="svo",
        display_name="Ours/SVO",
        implemented=True,
        pipeline_steps=(
            "extract_objects.py --method svo",
            "verify_objects.py --method svo --risk-threshold <tau>",
            "revise_captions.py",
        ),
    ),
    "vcd": MethodSpec(
        name="vcd",
        display_name="VCD",
        implemented=False,
        pipeline_steps=(),
        todo=(
            "Attach a reproducible Visual Contrastive Decoding implementation.",
            "Expose VCD decoding parameters through a YAML method config.",
            "Write outputs in the same caption/POPE JSONL schemas as Base before evaluation.",
        ),
        integration_notes=(
            "Keep the same prompt, max_new_tokens, decoding seed, and dataset splits as Base.",
            "Do not export VCD numbers unless generated by an implemented VCD pipeline.",
        ),
    ),
    "opera": MethodSpec(
        name="opera",
        display_name="OPERA",
        implemented=False,
        pipeline_steps=(),
        todo=(
            "Attach the official or validated OPERA decoding-intervention implementation.",
            "Expose OPERA-specific decoding parameters through a YAML method config.",
            "Write outputs in the same caption/POPE JSONL schemas as Base before evaluation.",
        ),
        integration_notes=(
            "Record dependency versions and any environment limitations before reporting results.",
            "Do not export OPERA numbers unless generated by an implemented OPERA pipeline.",
        ),
    ),
}


def get_method_spec(name: str) -> MethodSpec:
    """Return a method specification by name."""

    try:
        return METHOD_REGISTRY[name]
    except KeyError as exc:
        raise ValueError(f"Unknown method: {name}") from exc
